### ISSUE TITLE
The Keyspace website is unreachable

### ISSUE THREAD

**Issue by saintbarracosa** [Keyspace-cloud/web#8]
Hi!

The Keyspace website is unreachable. Is the website not working at the moment due to a known problem?

![keyspace](https://user-images.githubusercontent.com/121737136/211223341-d0f6fd60-b359-4f3c-abd3-971806aece0b.png)

**Comment by nimish-ks** [comment]
Hi @saintbarracosa 

Extremely sorry for the inconvenience. This was caused due to a misconfiguration on a DNS record that went unnoticed. 

The mobile app and the Keyspace service was not affected. We have taken measures to make sure this doesn't happen again in the future. You can track the status here: https://status.keyspace.cloud

In the future I would recommend using the Keyspace browser addon as it provides security benefits over the web app.

Keyspace Firefox addon: https://addons.mozilla.org/en-US/firefox/addon/keyspace
Chrome / Brave: Coming soon
